### ISSUE TITLE
Cannot download quiz content

### ISSUE THREAD

**Issue by eyanq** [ghandic/udemy_ripper#1]
Hi @ghandic, 

I've tried to use this extension to download an Udemy course quiz but unfortunately couldn't make it work. I've added a few breakpoints into the udemy.js code and check the intermediate output in browser console. The code could return `questions` object as well as the content for each question, but it couldn't create the `quiz` object.

example output:
![image](https://user-images.githubusercontent.com/2553211/62520401-a0d33900-b881-11e9-9aca-2cd3562637cc.png)

Hopefully you can help me to fix this. 
Cheers.

**Comment by ghandic** [comment]
Hey, I just used it on a new quiz and updated it for my situation... Could you give it ago now?

**Comment by ghandic** [comment]
Also once you have the json, I have just made this repo for making standalone quizes from the output of this. https://github.com/ghandic/quizgen

**Comment by eyanq** [comment]
It's working fine now and I could get the quiz json object. Thanks for your help.
